### ISSUE TITLE
Admin config for site color changes.

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/iowareview.org#14]
Each new TIR issue the client requests a color change to the website. Ideally we would write some configuration that could implement a class that could change the site colors.

**Comment by adamdelaney** [comment]
## Config.
- Implement hook_menu and add `http://iowareview.org.dd:8083/admin/config/user-interface/tir-theme`
- Build a form using the forms_api that implements two color inputs. We should be able to use HTML5 native input, i.e. `<input type="color">`
- The form should be a `system_settings_form($form)` form.

## Theming/Rendering
- Audit each css selector for the featured colors. There are 2 featured colors. Look in custom.css in the tir theme. 
- We need to remove those color/background-color values in the tir theme custom.css.
- We need to alter the input for the config form to update the input type to color. This may be done during the render or we could attach JS to change this type using a drupal.behavior.
- Attach css in a page_preprocess() and write back each selector with it's give color or background-color. We should be able to get this using a variable_get().

**Comment by GaryRidgway** [comment]
fixed in this commit. 

https://github.com/ITS-UofIowa/iowareview.org/commit/dc9aba099746f32baebd03e9f3b6c5938dd2fc91

still needs to be merged in.
