### ISSUE TITLE
Implement sitenow_media

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/iowareview.org#9]
sitenow_media is our media solution. It includes image, video and documents. Soon we will have rich media embeds like twitter, facebook and instagram.

**Comment by adamdelaney** [comment]
I think we just need to enable this module.

**Comment by GaryRidgway** [comment]
fixed with this commithttps://github.com/ITS-UofIowa/iowareview.org/commit/86e433eb566675ac73e933fc388201509d1b8eca
